pim_fhir_api_product_model_list:
  path: /product-models
  defaults: { _controller: pim_fhir_api.controller.product_model:listAction, _format: json }
  methods: [GET]

pim_fhir_api_product_model_get:
  path: /product-models/{code}
  defaults: { _controller: pim_fhir_api.controller.product_model:getAction, _format: json }
  methods: [GET]
  requirements:
    code: (.+$)(?<!/draft|/proposal)