######################################################################
# Copyright (c) 2020, VillageReach
# Licensed under the Non-Profit Open Software License version 3.0.
# SPDX-License-Identifier: NPOSL-3.0
######################################################################
parameters:
    pcmt.cis.entity.subscription.class:  PcmtCISBundle\Entity\Subscription

services:
    pcmt.cis.repository.subscription:
        class: PcmtCISBundle\Repository\SubscriptionRepository
        factory: 'doctrine.orm.entity_manager:getRepository'
        arguments: ['%pcmt.cis.entity.subscription.class%']
        tags:
            - { name: 'pim_repository' }

    pcmt.cis.subscription.normalizer:
        class: PcmtCISBundle\Normalizer\SubscriptionNormalizer
        autowire: true
        tags:
            - { name: pim_internal_api_serializer.normalizer, priority: 80 }

    pcmt.cis.constraint.required_field_constraint_validator:
        class: PcmtCISBundle\Validator\RequiredFieldConstraintValidator
        tags:
            - { name: validator.constraint_validator, alias: pcmt_cis_required_field_constraint_validator }

    pcmt.cis.remover.subscription:
        class: '%pim_catalog.remover.base.class%'
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@event_dispatcher'
            - '%pcmt.cis.entity.subscription.class%'