extensions:
  pcmt-rules-family-to-family-job-edit:
    module: pim/form/common/edit-form

  pcmt-rules-family-to-family-job-edit-main-image:
    module: pim/form/common/main-image
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: main-image
    config:
      path: bundles/pimui/images/illustrations/ImportXLSX.svg

  pcmt-rules-family-to-family-job-edit-user-navigation:
    module: pim/menu/user-navigation
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: user-menu
    config:
      userAccount: pim_menu.user.user_account
      logout: pim_menu.user.logout

  pcmt-rules-family-to-family-job-edit-breadcrumbs:
    module: pim/common/breadcrumbs
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: breadcrumbs
    config:
      tab: pim-menu-rules

  pcmt-rules-family-to-family-job-edit-cache-invalidator:
    module: pim/cache-invalidator
    parent: pcmt-rules-family-to-family-job-edit
    position: 1000

  pcmt-rules-family-to-family-job-edit-tabs:
    module: pim/form/common/form-tabs
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: content
    position: 100

  pcmt-rules-family-to-family-job-edit-properties:
    module: pim/job/common/edit/properties
    parent: pcmt-rules-family-to-family-job-edit-tabs
    aclResourceId: pcmt_permission_rules_edit
    targetZone: container
    position: 100
    config:
      tabTitle: pim_common.properties
      tabCode: pim-job-instance-properties

  pcmt-rules-family-to-family-job-description:
    module: pim/common/simple-view
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 200
    config:
      template: pcmt/rules/template/job/rules/family-copy-by-attribute-description

  pcmt-rules-family-to-family-job-edit-mapping-tab:
    module: pcmt/rules/job/rules/edit/mapping-tab
    parent: pcmt-rules-family-to-family-job-edit-tabs
    aclResourceId: pcmt_permission_rules_edit
    targetZone: container
    position: 120
    config:
      tabTitle: pcmt.rules.family_to_family_job.tab.attribute_mapping
      tabCode: pcmt-rules-family-to-family-job-edit-mapping

  pcmt-rules-family-to-family-job-edit-mapping:
    module: pcmt/rules/job/rules/edit/attribute-mapping
    parent: pcmt-rules-family-to-family-job-edit-mapping-tab
    targetZone: properties
    position: 120
    config:
      fieldCode: configuration.attributeMapping

  pcmt-rules-family-to-family-job-edit-history:
    module: pim/common/tab/history
    parent: pcmt-rules-family-to-family-job-edit-tabs
    targetZone: container
    aclResourceId: pcmt_permission_rules_view
    position: 130
    config:
      class: Akeneo\Tool\Component\Batch\Model\JobInstance
      title: pim_common.history
      tabCode: pim-job-instance-history

  pcmt-rules-family-to-family-job-edit-properties-code:
    module: pim/job/common/edit/field/text
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 100
    targetZone: properties
    config:
      fieldCode: code
      label: pim_common.code
      readOnly: true

  pcmt-rules-family-to-family-job-edit-properties-label:
    module: pim/job/common/edit/field/text
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 110
    targetZone: properties
    config:
      fieldCode: label
      label: pim_common.label
      readOnly: false

  pcmt-rules-family-to-family-job-edit-properties-source-family:
    module: pcmt/rules/job/field/select
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 155
    targetZone: properties
    config:
      fetcher: 'family'
      fieldCode: configuration.sourceFamily
      readOnly: false
      label: pcmt.rules.family_to_family_job.properties.source_family.title
      tooltip: pcmt.rules.family_to_family_job.properties.source_family.help

  pcmt-rules-family-to-family-job-edit-properties-destination-family:
    module: pcmt/rules/job/field/select
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 160
    targetZone: properties
    config:
      fetcher: 'family'
      fieldCode: configuration.destinationFamily
      readOnly: false
      label: pcmt.rules.family_to_family_job.properties.destination_family.title
      tooltip: pcmt.rules.family_to_family_job.properties.destination_family.help

  pcmt-rules-family-to-family-job-edit-properties-key-attribute:
    module: pcmt/rules/job/field/key-attribute-select
    parent: pcmt-rules-family-to-family-job-edit-properties
    position: 165
    targetZone: properties
    config:
      fetcher: key-attribute-for-rule
      sourceFamily: 'configuration.sourceFamily'
      destinationFamily: 'configuration.destinationFamily'
      fieldCode: configuration.keyAttribute
      readOnly: false
      label: pcmt.rules.family_to_family_job.properties.key_attribute.title

  pcmt-rules-family-to-family-job-edit-label:
    module: pim/job/common/edit/label
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: title
    position: 100

  pcmt-rules-family-to-family-job-edit-meta:
    module: pim/job/common/edit/meta
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: meta
    position: 100

  pcmt-rules-family-to-family-job-edit-secondary-actions:
    module: pim/form/common/secondary-actions
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: buttons
    position: 50

  pcmt-rules-family-to-family-job-edit-delete:
    module: pim/job/import/edit/delete
    parent: pcmt-rules-family-to-family-job-edit-secondary-actions
    targetZone: secondary-actions
    aclResourceId: pcmt_permission_rules_delete
    position: 100
    config:
      trans:
        title: confirmation.remove.import_profile
        content: pim_common.confirm_deletion
        success: pim_import_export.entity.job_instance.flash.delete.success
        failed: error.removing.job_instance
      redirect: pcmt_rules_profile_index

  pcmt-rules-family-to-family-job-edit-save-buttons:
    module: pim/form/common/save-buttons
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: buttons
    position: 120

  pcmt-rules-family-to-family-job-edit-save:
    module: pcmt/rules/job/rules/edit/save
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: buttons
    position: 0
    config:
      redirectPath: pcmt_rules_profile_show

  pcmt-rules-family-to-family-job-edit-state:
    module: pim/form/common/state
    parent: pcmt-rules-family-to-family-job-edit
    targetZone: state
    position: 900
    config:
      entity: pim_import_export.entity.job_instance.label

  pcmt-rules-family-to-family-job-edit-validation:
    module: pim/job/common/edit/validation
    parent: pcmt-rules-family-to-family-job-edit
